### ISSUE TITLE
Error while building with SvelteKit

### ISSUE THREAD

**Issue by sproott** [icflorescu/trpc-transformer#1]
The following error happens for me when building a SvelteKit app that uses trpc-transformer:

![image](https://user-images.githubusercontent.com/46423131/203089012-5b8c4a87-a3eb-4183-ae18-457bef8c80ea.png)

Steps to reproduce:

- clone [this repository containing a minimal example](https://github.com/sproott/trpc-transformer-error)
- install dependencies
- run the build script
- see error

**Comment by sproott** [comment]
Note that this happens on all package managers for me, not just pnpm.

**Comment by icflorescu** [comment]
This should be fixed in `v2.2.1`.
Feel free to reopen if it's not.

**Comment by sproott** [comment]
I see you've switched to esbuild, [tsup](https://tsup.egoist.dev/) is a nice to use tool built on it.

**Comment by icflorescu** [comment]
Thanks, will keep that in mind!
